In [1]:
from BertEmbedding import EmbeddingCreator

In [2]:
emb = EmbeddingCreator()

In [3]:
word_vector_dict = emb.createEmbeddingFirstTime('bert_embeddings')

<class 'numpy.ndarray'>
11788


11788it [6:24:37,  1.96s/it]


In [4]:
word_vector_dict['Crested_Auklet_0029_1824.jpg']

array([-8.78977716e-01, -1.97590902e-01,  2.13166788e-01,  7.54236996e-01,
       -1.18940644e-01, -1.29596084e-01,  9.07947600e-01,  1.93362355e-01,
       -1.46138385e-01, -9.99735057e-01, -3.29858691e-01,  5.88665545e-01,
        9.78756845e-01, -2.28454977e-01,  9.13416207e-01, -6.13190532e-01,
       -4.36356068e-01, -5.24157166e-01,  3.77056271e-01, -8.35626304e-01,
        5.91863513e-01,  9.28167820e-01,  4.18763012e-01,  2.06000060e-01,
        3.22302103e-01,  6.76004529e-01, -7.19706118e-01,  9.22298491e-01,
        9.47980881e-01,  6.74808383e-01, -7.30149567e-01,  1.32262722e-01,
       -9.84376788e-01, -1.87163115e-01, -1.75508961e-01, -9.81383026e-01,
        1.79733932e-01, -7.68138051e-01, -6.38554469e-02,  4.49661799e-02,
       -8.80247772e-01,  3.02370667e-01,  9.96934891e-01,  3.25311989e-01,
        1.97291151e-01, -2.44889617e-01, -9.99529541e-01,  1.96279228e-01,
       -8.85007322e-01,  1.96334869e-01,  1.57061487e-01,  8.37927237e-02,
        4.05753814e-02,  

In [5]:
word_vector_dict['Crested_Auklet_0029_1824.jpg'] - emb.createCustomEmbeddings('the bill of the bird is bright orange and the bird has white eye rings as well as black body feathers.')

<class 'numpy.ndarray'>
1


1it [00:02,  2.59s/it]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [ ]:
%run bert_based_model_batnorm-emb.ipynb

In [9]:
import pandas as pd

In [15]:
import numpy as np

In [17]:
sentence = 'hello'
t = np.array(sentence)

In [18]:
t

array('hello', dtype='<U5')

In [10]:
df = pd.read_csv('final.csv')h
df = df[1:10]

In [14]:
df['images'].values

array(['Crested_Auklet_0029_1824.jpg', 'Crested_Auklet_0074_794949.jpg',
       'Crested_Auklet_0045_794940.jpg', 'Crested_Auklet_0077_785257.jpg',
       'Crested_Auklet_0018_1817.jpg', 'Crested_Auklet_0041_794910.jpg',
       'Crested_Auklet_0066_785251.jpg', 'Crested_Auklet_0047_794918.jpg',
       'Crested_Auklet_0044_1825.jpg'], dtype=object)

In [1]:
import tensorflow_hub as hub
import tensorflow_text
import pandas as pd
import pickle
import re
import numpy as np


In [2]:
caps = pd.read_csv('final.csv')

In [3]:
caps.head()

images  \
0  Crested_Auklet_0001_794941.jpg   
1    Crested_Auklet_0029_1824.jpg   
2  Crested_Auklet_0074_794949.jpg   
3  Crested_Auklet_0045_794940.jpg   
4  Crested_Auklet_0077_785257.jpg   

                                            captions  
0  this bird is black all over its body with oran...  
1  the bill of the bird is bright orange and the ...  
2  this bird has smooth, dary gray feathers and a...  
3  this bird's head and body are all gray, but th...  
4  a large black bird has a gray colored breast, ...

In [4]:
caps.head(20)

images  \
0   Crested_Auklet_0001_794941.jpg   
1     Crested_Auklet_0029_1824.jpg   
2   Crested_Auklet_0074_794949.jpg   
3   Crested_Auklet_0045_794940.jpg   
4   Crested_Auklet_0077_785257.jpg   
5     Crested_Auklet_0018_1817.jpg   
6   Crested_Auklet_0041_794910.jpg   
7   Crested_Auklet_0066_785251.jpg   
8   Crested_Auklet_0047_794918.jpg   
9     Crested_Auklet_0044_1825.jpg   
10  Crested_Auklet_0073_785248.jpg   
11  Crested_Auklet_0013_794914.jpg   
12  Crested_Auklet_0039_794944.jpg   
13  Crested_Auklet_0021_794938.jpg   
14  Crested_Auklet_0028_794951.jpg   
15  Crested_Auklet_0067_785249.jpg   
16  Crested_Auklet_0076_785252.jpg   
17  Crested_Auklet_0059_794929.jpg   
18  Crested_Auklet_0012_794960.jpg   
19  Crested_Auklet_0003_794962.jpg   

                                             captions  
0   this bird is black all over its body with oran...  
1   the bill of the bird is bright orange and the ...  
2   this bird has smooth, dary gray feathers and a...  
3   this bird's head and body are all gray, but th...  
4   a large black bird has a gray colored breast, ...  
5   this bird has an orange bill, with solid brown...  
6   gray and black feathered bird with feathers ha...  
7   this unusual bird has a plume above its orange...  
8   the bird has a tiny eye ring that is white and...  
9   medium sized gray bird with medium orange beak...  
10  black bird with white eye, short tail feathers...  
11  this bird is mostly gray, with a short orange ...  
12  small black bird with a small curved orange be...  
13  this bird is all black with an orange beak and...  
14  the mainly gray bird has a white eye with a wh...  
15  a tall erect bird, mostly black, with webbed f...  
16  this intense looking bird is medium in size, h...  
17  this bird is black and white in color, with a ...  
18  the bird is dark gray in color, has a stubby b...  
19  this bird is mostly gray with a bright orange ...

In [5]:
def create_image_csv():
    rootdir = 'images/birds/CUB_200_2011/images'
    df = pd.DataFrame(columns=['images'])
    for subdir, dirs, files in os.walk(rootdir):
        for file in files:
            filepath = subdir + os.sep + file
            if filepath.endswith(".jpg") or filepath.endswith(".jpeg") or filepath.endswith(".png"):
                df.loc[len(df)] = [file]
    df.to_csv("intermediate_results.csv", index=False)

In [6]:
def create_final_csv():
    rootdir = '/captions/text_c10'
    images = pd.read_csv('intermediate_results.csv')
    images['captions'] = 'abc'
    print(images.head())
    for subdir, dirs, files in os.walk(rootdir):
        for file in files:
            filepath = subdir + os.sep + file
            if filepath.endswith(".txt"):
                with open(filepath) as f:
                    content = f.readlines()
                content = [x.strip() for x in content]
                t = file.replace('.txt', '.jpg')
                images.loc[images['images'] == t, 'captions'] = content[random.randint(0, 1)]
    images.to_csv("final.csv", index=False)


In [7]:
def clean_and_tokenize_comments_for_image(comment):
    stop_words = ['a', 'and', 'of', 'to']
    punctuation = r"""!"#$%&'()*+,./:;<=>?@[\]^_`…’{|}~"""
    comments_without_punctuation = [s.translate(str.maketrans(' ', ' ', punctuation)) for s in comment]
    sentences = []

    for q_w_c in comments_without_punctuation:
        q_w_c = re.sub(r"-(?:(?<!\b[0-9]{4}-)|(?![0-9]{2}(?:[0-9]{2})?\b))", ' ', q_w_c)  # replace with space

        temp_tokens = word_tokenize(str(q_w_c).lower())
        tokens = [t for t in temp_tokens if t not in stop_words]
        sentences.append(tokens)
    return sentences


In [8]:
def create_feature_vectors_for_single_comment(word2vec_model, cleaned_comments, image_names):
    vectorized_list = []
    image_list = []

    for comments, image in tqdm(zip(cleaned_comments, image_names)):
        result_array = np.empty((0, 768))
        for word in comments:
            #print(word)
            w = bert_preprocess_model([word])
            w = word2vec_model(w)
            w = w['pooled_output']
            #print(len(w))
            #print(w.numpy())
            result_array = np.append(result_array, w, axis=0)

        vectorized_list.append(np.mean(result_array, axis=0).astype('float32'))
        image_list.append(image)

    return image_list, np.array(vectorized_list)



In [9]:
from tqdm import tqdm

In [10]:
def create_sentence_embeddings():
    df = pd.read_csv('final.csv')
    df = df[1:10]
    model = bert_model
    cleaned_captions = df['captions'].values
    cleaned_captions = bert_preprocess_model(cleaned_captions)
    image_names = df['images'].values
    print('Done tokenizing....')
    i, c = create_feature_vectors_for_single_comment(model, cleaned_captions, image_names)
    word_vector_dict = dict(zip(i, c))
    pickle.dump(word_vector_dict, open('1_test_word_vector_min_bird' + ".p", "wb"))
    print('Done')
    print(i)
    print()
    return c


In [11]:
c = create_sentence_embeddings()

NameError: name 'bert_model' is not defined

In [181]:
c[0]

array([-8.80453765e-01, -2.30016977e-01,  1.53982677e-02,  7.63145745e-01,
       -1.67636186e-01, -1.12899035e-01,  9.20433581e-01,  2.31789663e-01,
       -1.92173526e-01, -9.99809325e-01, -1.48938507e-01,  5.04856467e-01,
        9.74133551e-01,  2.51672100e-02,  9.12574768e-01, -6.27402663e-01,
       -3.41317058e-01, -5.57229817e-01,  3.86493057e-01, -8.32161784e-01,
        5.95441282e-01,  8.90097916e-01,  4.09509450e-01,  2.50163227e-01,
        3.93467665e-01,  5.93674242e-01, -6.57673061e-01,  9.15036798e-01,
        9.51860309e-01,  7.05915213e-01, -7.49266684e-01,  1.42062679e-01,
       -9.77758586e-01, -2.60669142e-01, -1.55464560e-01, -9.79721069e-01,
        1.93323925e-01, -7.69981802e-01, -9.83245596e-02,  2.95864381e-02,
       -8.72071326e-01,  2.98111081e-01,  9.95922685e-01,  2.26048753e-01,
        9.48943347e-02, -3.52533966e-01, -9.99241948e-01,  2.67680496e-01,
       -8.80547166e-01,  2.29656994e-01,  1.56744406e-01, -3.83794233e-02,
        1.54842883e-01,  

In [64]:
df = pd.read_csv('final.csv')
df = df[1:2]

In [65]:
df

images  \
1  Crested_Auklet_0029_1824.jpg   

                                            captions  
1  the bill of the bird is bright orange and the ...

In [66]:
df['captions'].values

array(['the bill of the bird is bright orange and the bird has white eye rings as well as black body feathers.'],
      dtype=object)

cleaned_captions = clean_and_tokenize_comments_for_image(df['captions'].values)

In [67]:
cleaned_captions = df['captions'].values
cleaned_captions = bert_preprocess_model(cleaned_captions)

In [55]:
cleaned_captions.keys()

dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

In [60]:
df

Empty DataFrame
Columns: [images, captions]
Index: []

In [57]:
df

Empty DataFrame
Columns: [images, captions]
Index: []